2 neue Optionen, wie man mit dem erneuten Auflegen einer Karte umgehen kann
tonuino/TonUINO-TNG pull request #137
Opened 2023-11-19 12:04 UTC by r-schmidt

2023-11-19 13:04 UTC, boerge1 commented
Nice idea!

2023-11-19 14:33 UTC, boerge1 requested changes

2023-11-19 18:39 UTC, r-schmidt commented on src/state_machine.cpp
> +        transit<Play>();
Wasn't sure if it always is in Play state here. I changed it now but can't test it because the Tonuino is back with my nephew for the next weeks.

2023-11-20 09:54 UTC, boerge1 commented on src/state_machine.cpp
> +        transit<Play>();
> Wasn't sure if it always is in Play state here. 

This the` react()` function of the state class `Play`, so it must be in state Play

2023-11-20 09:55 UTC, merged

2023-11-20 10:18 UTC, boerge1 commented
This pull request will be merge to main in pull request #139